#!/bin/bash
# $Id: tw-email-to,v 1.6 2011/02/23 00:33:53 bruno Exp $
# $Log: tw-email-to,v $
# Revision 1.6  2011/02/23 00:33:53  bruno
# fix to send tripwire reports to multiple recipients.
#
# Revision 1.5  2009/07/01 22:03:59  bruno
# fixes
#
# Revision 1.4  2009/05/26 22:21:31  bruno
# changed 'tripwire' 'mail(to)' from an app_global to a global attribute
#
# Revision 1.3  2007/07/13 17:30:34  phil
# Use the rocks command line to store the emailto for tripwire
#
# Revision 1.2  2006/09/18 23:06:39  phil
# Don't fail if mysql isn't running ...
#
# Revision 1.1  2005/10/16 04:46:07  phil
# Generic method to set the email address for report recipients
#

#
# A small script to read email addresses that tripwire cron sends email to
#

# See if we can get the attribute without error
/opt/rocks/bin/rocks report host attr localhost | grep tripwire_mail 2>1 > \
	/dev/null 
retcode=$?

if [ $retcode -eq 0 ]; then 
	/opt/rocks/bin/rocks report host attr localhost | grep tripwire_mail \
		| awk -F: '{print $2}'
else
	echo "root@localhost"  
fi

